// imgclasse: "retrato" (h>w), "quadrada" (h~=w), "paisagem" (w>h)
// + classes individuais para exceções de object-position
export const eventos = [
  { ano: 1945, titulo: "Memex", tipo: "software", categoria: "Conceito de hipertexto", imagem: "img/memex.png", imagemdesc: "Vannevar Bush (1945)", imgclasse: "paisagem", resumo: "Vannevar Bush descreve no ensaio \u201cAs We May Think\u201d uma máquina conceitual capaz de armazenar e ligar documentos por associação. Nunca foi construída, mas plantou a ideia de hipertexto e de interface baseada em ligações." },
  { ano: 1950, titulo: "Cartões perfurados e teletipo", tipo: "hardware", categoria: "Entrada por lote", imagem: "img/cartao-perfurado.png", imagemdesc: "Cartão perfurado", imgclasse: "paisagem", resumo: "A interação acontecia por lotes: o programador furava cartões e recebia a resposta impressa horas depois. Não havia diálogo em tempo real entre humano e máquina." },
  { ano: 1963, titulo: "Sketchpad", tipo: "software", categoria: "Interface gráfica", imagem: "img/sketchpad.png", imagemdesc: "Sketchpad (1963)", imgclasse: "paisagem", resumo: "Ivan Sutherland cria o primeiro programa de desenho interativo, manipulado com uma caneta óptica diretamente na tela. É o embrião das interfaces gráficas e da computação visual." },
  { ano: 1964, titulo: "Mouse", tipo: "hardware", categoria: "Dispositivo apontador", imagem: "img/mouse.png", imagemdesc: "Primeiro mouse de Engelbart (1964)", imgclasse: "quadrada", resumo: "Douglas Engelbart e Bill English constroem o primeiro mouse, uma caixa de madeira com duas rodas. Ele transforma o movimento da mão em um ponteiro na tela — o gesto que definiria décadas de uso." },
  { ano: 1968, titulo: "A Mãe de Todas as Demos", tipo: "software", categoria: "Sistema interativo", imagem: "img/engelbart.png", imagemdesc: "Douglas Engelbart", imgclasse: "engelbart", resumo: "Engelbart apresenta ao vivo mouse, janelas, hipertexto, videoconferência e edição colaborativa. A demonstração antecipa quase tudo que usamos hoje em interfaces pessoais." },
  { ano: 1971, titulo: "Correio eletrônico (e-mail)", tipo: "software", categoria: "Mensageiro eletrônico", imagem: "img/tomlinson.png", imagemdesc: "Ray Tomlinson", imgclasse: "tomlinson", resumo: "Ray Tomlinson envia a primeira mensagem entre computadores diferentes e escolhe o símbolo \u201c@\u201d para separar usuário e máquina. Nasce o primeiro grande mensageiro eletrônico." },
  { ano: 1973, titulo: "Xerox Alto", tipo: "hardware", categoria: "Computador pessoal / GUI", imagem: "img/xerox-alto.png", imagemdesc: "Xerox Alto (1973)", imgclasse: "retrato", resumo: "Primeiro computador pensado para uma pessoa, com tela de mapa de bits, mouse e janelas. Reúne fisicamente os elementos da interface gráfica moderna." },
  { ano: 1981, titulo: "Xerox Star", tipo: "software", categoria: "Sistema operacional gráfico", imagem: "img/xerox-star.png", imagemdesc: "Xerox Star (1981)", imgclasse: "retrato", resumo: "Primeiro sistema comercial com metáfora de mesa de trabalho: ícones, pastas, documentos e o gesto de \u201capontar e clicar\u201d. Define a gramática visual dos sistemas operacionais." },
  { ano: 1984, titulo: "Apple Macintosh", tipo: "software", categoria: "Sistema operacional gráfico", imagem: "img/macintosh.png", imagemdesc: "Apple Macintosh (1984)", imgclasse: "quadrada", resumo: "Populariza a interface gráfica para o grande público a um preço acessível. A partir dele, mexer no computador deixa de exigir digitar comandos de texto." },
  { ano: 1985, titulo: "Microsoft Windows 1.0", tipo: "software", categoria: "Sistema operacional gráfico", imagem: "img/windows1.png", imagemdesc: "Windows 1.0 (1985)", imgclasse: "paisagem", resumo: "Leva a interface de janelas ao ecossistema de PCs compatíveis, iniciando a linhagem de sistemas operacionais mais usada do mundo nas décadas seguintes." },
  { ano: 1988, titulo: "IRC", tipo: "software", categoria: "Mensageiro eletrônico", imagem: "img/irc.png", imagemdesc: "IRC", imgclasse: "paisagem", resumo: "O Internet Relay Chat cria as salas de bate-papo em tempo real, base cultural de todos os mensageiros instantâneos que viriam depois." },
  { ano: 1990, titulo: "World Wide Web e o navegador", tipo: "software", categoria: "Navegador / hipertexto", imagem: "img/tbl.png", imagemdesc: "Tim Berners-Lee", imgclasse: "tbl", resumo: "Tim Berners-Lee cria a Web e o primeiro navegador. A interface passa a ser o hipertexto navegável por links — a ideia do Memex, enfim realizada." },
  { ano: 1996, titulo: "ICQ", tipo: "software", categoria: "Mensageiro eletrônico", imagem: "img/icq.png", imagemdesc: "ICQ", imgclasse: "paisagem", resumo: "Primeiro mensageiro instantâneo de massa, com lista de contatos e o inesquecível som \u201cUh-oh\u201d. Firma o bate-papo pessoal como hábito cotidiano." },
  { ano: 2007, titulo: "iPhone e a tela multitoque", tipo: "hardware", categoria: "Interface por toque", imagem: "img/iphone.png", imagemdesc: "iPhone 1ª geração (2007)", imgclasse: "paisagem", resumo: "A tela sensível a múltiplos toques elimina o teclado físico e o stylus. Gestos como deslizar e pinçar tornam-se a nova linguagem de interação direta." },
  { ano: 2011, titulo: "Assistentes de voz (Siri)", tipo: "software", categoria: "Interface por voz", imagem: "img/siri.png", imagemdesc: "Siri (2011)", imgclasse: "paisagem", resumo: "A interface deixa de exigir toque ou clique: fala-se com o dispositivo em linguagem natural. Começa a era da interação por voz no dia a dia." },
  { ano: 2016, titulo: "Realidade virtual de consumo", tipo: "hardware", categoria: "Interface imersiva", imagem: "img/oculus.png", imagemdesc: "Oculus Rift (2016)", imgclasse: "quadrada", resumo: "Óculos como o Oculus Rift levam a interface para o espaço tridimensional, onde o corpo e o olhar passam a ser os controles." },
  { ano: 2022, titulo: "Interfaces conversacionais com IA", tipo: "software", categoria: "Interface conversacional", imagem: "img/chatgpt.png", imagemdesc: "ChatGPT (2022)", imgclasse: "paisagem", resumo: "Ferramentas como o ChatGPT popularizam o diálogo em linguagem natural como forma de operar o computador — a interface passa a compreender intenção, não só comandos." },
];
